import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# =========================
# PAGE TITLE
# =========================

st.title("📊 Sales Analytics")

st.info("""
This page provides sales performance analysis including
revenue distribution and monthly revenue trends.
""")

# =========================
# LOAD DATA
# =========================

df = pd.read_csv("amazon_dashboard_data.csv")

df['purchase_date'] = pd.to_datetime(df['purchase_date'])

# =========================
# SALES KPIs
# =========================

total_revenue = df['final_price'].sum()

total_sales = len(df)

col1, col2 = st.columns(2)

with col1:
    st.metric(
        "Total Revenue",
        f"{total_revenue:,.0f}"
    )

with col2:
    st.metric(
        "Total Sales",
        f"{total_sales:,}"
    )

# =========================
# REVENUE BY CATEGORY
# =========================

st.markdown("---")

st.subheader("📈 Revenue by Category")

category_sales = (
    df.groupby('category')['final_price']
    .sum()
    .sort_values(ascending=False)
)

fig1, ax1 = plt.subplots(figsize=(7,4))

category_sales.plot(
    kind='bar',
    ax=ax1
)

ax1.set_title("Revenue Generated by Product Category")
ax1.set_xlabel("Category")
ax1.set_ylabel("Revenue")

st.pyplot(fig1)

# =========================
# MONTHLY REVENUE TREND
# =========================

st.markdown("---")

st.subheader("📅 Monthly Revenue Trend")

monthly_revenue = (
    df.groupby(
        df['purchase_date'].dt.to_period('M')
    )['final_price']
    .sum()
)

monthly_revenue.index = monthly_revenue.index.astype(str)

fig2, ax2 = plt.subplots(figsize=(8,4))

monthly_revenue.plot(
    marker='o',
    linewidth=2,
    ax=ax2
)

ax2.set_title("Monthly Revenue Trend")
ax2.set_xlabel("Month")
ax2.set_ylabel("Revenue")

plt.xticks(rotation=45)

st.pyplot(fig2)

# =========================
# TOP REVENUE CATEGORY
# =========================

st.markdown("---")

top_category = category_sales.idxmax()

top_revenue = category_sales.max()

st.success(
    f"🏆 Highest Revenue Category: {top_category} "
    f"(Revenue: {top_revenue:,.0f})"
)